## Source: https://github.com/marketplace/actions/push-a-directory-to-another-repository

name: Push File

on:
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:
    inputs:
      manual:
        required: false
        type: boolean
        description: "Manual"
        

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes source files
        uses: gh4-io/copy-helm@v0.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: "."
          destination_repo: "gh4-io/charts"
          destination_branch: "master"
          destination_folder: "charts/papermerge"
          user_email: "jason@gh4.io"
          user_name: "gh4-io"
          commit_msg: "Push post update"
          debug: "true"
