apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.global.conf.app.django_settings_module | quote }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.global.conf.app.superuser.username | quote  }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.global.conf.app.superuser.email | quote }}
  PAPERMERGE__DATABASE__TYPE: {{ .Values.global.conf.db.type | quote }}
  PAPERMERGE__DATABASE__USER: {{ .Values.global.conf.db.user | quote }}
  PAPERMERGE__DATABASE__NAME: {{ .Values.global.conf.db.name | quote }}
  PAPERMERGE__DATABASE__HOST: {{ .Values.global.conf.db.host | quote }}
  PAPERMERGE__REDIS__HOST: {{ .Values.global.conf.redis.host | quote }}
{{- if .Values.global.conf.redis.port }}
  PAPERMERGE__REDIS__PORT: {{ .Values.global.conf.redis.port | quote }}
{{- end }}
  PAPERMERGE__MAIN__MEDIA_ROOT: {{ .Values.global.conf.app.media_dir | quote }}
  PAPERMERGE__MAIN__TIMEZONE: {{ .Values.global.conf.app.tz | quote }}
{{- if .Values.global.conf.es.enabled }}
  PAPERMERGE_ELASTICSEARCH_HOSTS: {{ .Values.global.conf.es.hosts | quote }}
  PAPERMERGE_ELASTICSEARCH_PORT: {{ .Values.global.conf.es.port | quote }}
{{- end }}
{{- if .Values.global.conf.app.logging_config }}
  PAPERMERGE__MAIN__LOGGING_CFG: {{ .Values.global.conf.app.logging_config | quote }}
{{- end }}
